name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Persist npm cache
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

            - name: Persist Eleventy .cache
              uses: actions/cache@v4
              with:
                  path: ./.cache
                  key: ${{ runner.os }}-eleventy-fetch-cache

            - run: npm install

            - name: Configure Git
              run: |
                  git config --global user.email "stephane@pntbr.fr"
                  git config --global user.name "pntbr"

            - name: Build Project
              run: npx @11ty/eleventy

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist